name: "Chromium"
version: "1.0.0"
slug: "chromium"
panel_icon: "mdi:chromium"
description: "Docker container for Chromium"
url: "https://github.com/AngeloMontesano/ha-addons"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
apparmor: false
panel_admin: false
map:
  - share:rw
ingress: true
ingress_port: 5800
ports:
  5800/tcp: null
  5900/tcp: null
  9222/tcp: null
environment:
  # Required to write to /data
  USER_ID: "0"
  KEEP_APP_RUNNING: "1"
# Sound support (forward audio to your host), not tested
devices:
  - /dev/snd
# Map a working PulseAudio setup into the container
audio: true
image: "https://github.com/AngeloMontesano/ha-addons"
# To pass options as environment variables (thanks to legacy mode), they must be either "int" or "str" ("str?" will be ignored).
legacy: true
options:
  PASSWORD: "Start123"
  CUSTOM_USER: "ha-addons"
  LC_ALL: "en_US.UTF-8"
  TZ: "Etc/UTC"

schema:
  PASSWORD: str
  CUSTOM_USER: str
  LC_ALL: str
  TZ: str
